{
 "title": "Zeebe",
 "description": "High-level Zeebe.io cluster metrics via Prometheus.",
 "tags": [
  "zeebe",
  "workflow"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "label": "Cluster",
    "query": "label_values(zb_broker_info,cluster)"
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": "label_values(zb_workflow_instance_events_count{cluster=\"$cluster\"},topic)"
   }
  ]
 },
 "panels": [
  {
   "title": "Workflow instance events ($topic)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ops", "label": "Events/s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zb_workflow_instance_events_count{cluster=\"$cluster\",topic=\"$topic\"}[15s])) without (partition)",
     "legendFormat": "{{ type }}"
    }
   ]
  },
  {
   "title": "Storage write throughput ($topic)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "Bps", "label": "Write throughput" }
   ],
   "targets": [
    {
     "expr": "sum(rate(zb_storage_fs_total_bytes{cluster=\"$cluster\",topic=\"$topic\"}[15s])) without (partition)",
     "legendFormat": "filesystem"
    }
   ]
  },
  {
   "title": "Network throughput",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bps", "label": "in (-) / out (+)" }
   ],
   "targets": [
    {
     "expr": "rate(zb_transport_receive_bytes[15s]) * -8",
     "legendFormat": "{{ transport }}_in"
    },
    {
     "expr": "rate(zb_transport_transmit_bytes[15s]) * 8",
     "legendFormat": "{{ transport }}_out"
    }
   ]
  },
  {
   "title": "Operations",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 7, "x": 12, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(rate(zb_streamprocessor_events_count{cluster=\"$cluster\",action!=\"written\"}[15s]))"
    }
   ]
  }
 ]
}