{
 "title": "Zeebe Diagnostics",
 "description": "Low-level diagnostic Zeebe.io broker metrics via Prometheus.",
 "tags": [
  "zeebe",
  "broker"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "cluster",
    "query": "label_values(zb_broker_info,cluster)"
   },
   {
    "name": "node",
    "query": "label_values(zb_broker_info,node)"
   }
  ]
 },
 "panels": [
  {
   "title": "Broker node",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "zb_broker_info{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "{{ node }}"
    }
   ]
  },
  {
   "title": "Broker version",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 12, "x": 12, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "zb_broker_info{cluster=\"$cluster\",node=\"$node\"}",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "Scheduler task execution",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Task executions/s" }
   ],
   "targets": [
    {
     "expr": "rate(zb_scheduler_task_execution_count{cluster=\"$cluster\",node=\"$node\"}[15s])",
     "legendFormat": "{{ task }}"
    }
   ]
  },
  {
   "title": "Scheduler threads usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "short", "label": "Jobs/s" }
   ],
   "targets": [
    {
     "expr": "rate(zb_scheduler_thread_job_count{cluster=\"$cluster\",node=\"$node\"}[15s])",
     "legendFormat": "{{ thread }}"
    }
   ]
  },
  {
   "title": "Scheduler thread actions",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Actions/s" }
   ],
   "targets": [
    {
     "expr": "rate(zb_scheduler_thread_task_count{cluster=\"$cluster\",node=\"$node\"}[15s])",
     "legendFormat": "{{ thread }} - {{ type }}"
    }
   ]
  },
  {
   "title": "Streamprocessor events",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "short", "label": "Events/s" }
   ],
   "targets": [
    {
     "expr": "rate(zb_streamprocessor_events_count{cluster=\"$cluster\",node=\"$node\"}[15s])",
     "legendFormat": "{{ processor }} - {{ topic }}:{{ partition }} - {{ action }}"
    }
   ]
  },
  {
   "title": "Buffer fragments written",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Fragments/s" }
   ],
   "targets": [
    {
     "expr": "rate(zb_buffer_fragments_written{cluster=\"$cluster\",node=\"$node\"}[15s])",
     "legendFormat": "{{ buffer }}"
    }
   ]
  },
  {
   "title": "Buffer fragments read",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Fragments/s" }
   ],
   "targets": [
    {
     "expr": "rate(zb_buffer_fragments_read{cluster=\"$cluster\",node=\"$node\"}[15s])",
     "legendFormat": "{{ buffer }} - {{ subscription }}"
    }
   ]
  }
 ]
}